---
# tasks file for users
- name: Add users
  ansible.builtin.user:
    name: "{{ item }}"
    state: present
  with_items:
  - ben
  - johnd
  - lisa
- name: Ensure group "somegroup" exists
    ansible.builtin.group:
      name: "{{ item }}"
      state: present
    with_items:
    - DevOps